<?php
/**
 * Plugin Name:       {{NAME}}
 * Description:       {{DESCRIPTION}} Add the [{{SHORTCODE}}] shortcode to any page.
 * Version:           {{VERSION}}
 * Requires at least: 5.8
 * Requires PHP:      7.4
 * Author:            Tafseer
 * License:           GPL-2.0-or-later
 * Text Domain:       {{SLUG}}
 */

// Generated by plugin/build.py from plugin/src. Edit the source, not this file.

namespace {{NAMESPACE}};

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const VERSION   = '{{VERSION}}';
const SHORTCODE = '{{SHORTCODE}}';
// The one authority this plugin reads from, or '' to let the visitor choose.
const SOURCE    = '{{SOURCE}}';
// REST route under /wp-json/tafseer/v1.
const ROUTE     = '{{ROUTE}}';
const API_URL   = 'http://72.60.34.215/api/dreams';

define( __NAMESPACE__ . '\DIR', plugin_dir_path( __FILE__ ) );
define( __NAMESPACE__ . '\URL', plugin_dir_url( __FILE__ ) );

require_once DIR . 'includes/rest-proxy.php';

// Every Tafseer plugin shares these handles, so with several active the assets load once.
add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\register_assets' );
function register_assets() {
	wp_register_style(
		'tafseer-fonts',
		'https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=Inter:wght@400;500;600;700&family=Lora:wght@500;600;700&family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap',
		array(),
		null
	);
	wp_register_style( 'tafseer-app', URL . 'assets/css/tafseer.css', array( 'tafseer-fonts' ), VERSION );
	wp_register_script( 'tafseer-result', URL . 'assets/js/result.js', array(), VERSION, true );
	wp_register_script( 'tafseer-app', URL . 'assets/js/app.js', array( 'tafseer-result' ), VERSION, true );

	// Load the styles in <head> when we can see the shortcode, to avoid a flash of unstyled form.
	// Page builders keep content elsewhere; the shortcode callback enqueues as a fallback.
	$post = get_post();
	if ( $post && has_shortcode( $post->post_content, SHORTCODE ) ) {
		wp_enqueue_style( 'tafseer-app' );
	}
}

add_shortcode( SHORTCODE, __NAMESPACE__ . '\render_shortcode' );
function render_shortcode() {
	wp_enqueue_style( 'tafseer-app' );
	wp_enqueue_script( 'tafseer-app' );

	$source  = SOURCE;
	$api_url = rest_url( 'tafseer/v1/' . ROUTE );
	$uid     = wp_unique_id( 'tafseer-' );

	ob_start();
	include DIR . 'templates/app.php';
	return ob_get_clean();
}
